# Generated by Django 5.2.15 on 2026-06-21 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eveonline', '0025_remove_evecharacter_last_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllianceMoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('solar_system_name', models.CharField(blank=True, max_length=255)),
                ('ore_category', models.CharField(default='R64', max_length=50)),
                ('moon_type', models.CharField(choices=[('public', 'Public'), ('event', 'Event')], default='public', max_length=20)),
                ('is_tax_free', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OreCategory',
            fields=[
                ('type_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ore_category', models.CharField(max_length=50, unique=True)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_link', to='eveonline.evecharacter')),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_alts', to='eveonline.evecharacter')),
            ],
        ),
        migrations.CreateModel(
            name='FleetSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ore_type_id', models.PositiveIntegerField(blank=True, null=True)),
                ('ore_category', models.CharField(blank=True, max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('exclude_from_billing', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eveonline.evecharacter')),
                ('moon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='miningtax.alliancemoon')),
            ],
        ),
        migrations.CreateModel(
            name='MoonRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moon_name', models.CharField(max_length=255)),
                ('structure_name', models.CharField(blank=True, max_length=255)),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eveonline.evecorporationinfo')),
            ],
        ),
        migrations.CreateModel(
            name='AllianceBillingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('total_mined_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('mining_tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('moon_rental_total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_due', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('category_snapshot', models.JSONField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eveonline.evecorporationinfo')),
            ],
            options={
                'unique_together': {('corporation', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='MiningLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('solar_system_id', models.BigIntegerField(blank=True, null=True)),
                ('solar_system_name', models.CharField(blank=True, max_length=255)),
                ('type_id', models.PositiveIntegerField()),
                ('type_name', models.CharField(blank=True, max_length=255)),
                ('quantity', models.BigIntegerField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mining_entries', to='eveonline.evecharacter')),
            ],
            options={
                'unique_together': {('character', 'date', 'type_id', 'solar_system_id')},
            },
        ),
    ]
