# Generated by Django 5.2.15 on 2026-06-23 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miningtax', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CharacterLink',
        ),
    ]
